version: '3.8'

services:
  frontend:
    image: frontend
      #args:
      # - REACT_APP_SERVICES_HOST=/services/m
    ports:
      - "89:80"
      - "3443:443"
    networks:
      - frontend
      - backend

  backend:
    image: backend
    ports:
      - "3009:3000"
      - "2443:443"
    networks:
      - backend

networks:
  frontend:
  backend:
