name: APP Publish Docker image

on:
  push:
    branches:
      - fix_auth_prod
  workflow_run:
    workflows:
      - "Release"
    types:
      - completed
    branches:
      - master
    paths:
      - 'apps/frontend/**'
      - 'prisma/**'
      - '.github/workflows/release-docker-app.yml'
      - 'package-lock.json'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: eastolfi/santoral

jobs:
  build-and-push-app:
    runs-on: ubuntu-latest

    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password
      # that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Create env file
        run: |
          touch apps/frontend/.env.local
          echo NG_APP_AUTH0_DOMAIN=${{secrets.AUTH0_DOMAIN}} >> apps/frontend/.env.local
          echo NG_APP_AUTH0_CLIENT_ID=${{secrets.AUTH0_CLIENT_ID}} >> apps/frontend/.env.local
          echo NG_APP_AUTH0_AUDIENCE=${{secrets.AUTH0_AUDIENCE}} >> apps/frontend/.env.local

      - name: Create certificates for NgInx
        run: |
          touch apps/frontend/nginx/certs/nginx.crt
          echo "${{secrets.APP_NGINX_CERT}}" >> apps/frontend/nginx/certs/nginx.crt
          touch apps/frontend/nginx/certs/nginx.key
          echo "${{secrets.APP_NGINX_CERT_KEY}}" >> apps/frontend/nginx/certs/nginx.key

      - run: npx nx build frontend

      # This step uses [docker/metadata-action](https://github.com/docker/metadata-action#about) to extract tags and labels that will be applied to the specified image. The `id` "meta" allows the output of this step to be referenced in a subsequent step. The `images` value provides the base name for the tags and labels.
      # https://docs.docker.com/build/ci/github-actions/manage-tags-labels/
      # https://github.com/docker/metadata-action#flavor-input
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      # This step uses the `docker/build-push-action` action to build the image, based on your repository's `Dockerfile`. If the build succeeds, it pushes the image to GitHub Packages.
      # It uses the `context` parameter to define the build's context as the set of files located in the specified path. For more information, see "[Usage](https://github.com/docker/build-push-action#usage)" in the README of the `docker/build-push-action` repository.
      # It uses the `tags` and `labels` parameters to tag and label the image with the output from the "meta" step.
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: apps/frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
